name: CI
on: push

jobs:

  deploy:
    name: Deploy challenge
    runs-on: buildjet-16vcpu-ubuntu-2204
    needs: cancel

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run container
      run: docker-compose up -d 
    
    - uses: apogiatzis/ngrok-tunneling-action@<VERSION>
      with:
        timeout: 6h
        port: 4000
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
